# Generated by Django 3.1.1 on 2021-06-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Schedule Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Submission')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
            ],
            options={
                'verbose_name': 'Scheduled Lesson',
                'verbose_name_plural': 'Scheduled Lessons',
            },
        ),
    ]
