# Generated by Django 3.1.1 on 2021-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210626_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Creation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modification'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='schedulelesson',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
